#麺テーブル
#レベル1
Noodle.create(level: 1, sentence: "麺、少しムチとした食感のもの。")
Noodle.create(level: 1, sentence: "麺、カタメすぎる仕上がり。")
Noodle.create(level: 1, sentence: "麺、プルプルすぎる食感のもの。")
Noodle.create(level: 1, sentence: "麺、柔らかめすぎる仕上がり。")
Noodle.create(level: 1, sentence: "麺、ズババと啜れちゃう物足りないもの。")
Noodle.create(level: 1, sentence: "麺、汁染みすぎた仕上がり。")
Noodle.create(level: 1, sentence: "麺、クニュクニュすぎる食感のもの。")
Noodle.create(level: 1, sentence: "麺、ウマい汁あと一歩染みこんでほしい仕上がり。")
Noodle.create(level: 1, sentence: "麺、ウマ味凝縮あと一歩な仕上がり。")
Noodle.create(level: 1, sentence: "麺、少し歯切れ悪い仕上がり。")
#レベル2
Noodle.create(level: 2, sentence: "麺、カタメな食感のもの。")
Noodle.create(level: 2, sentence: "麺、カタメな仕上がりのもの。")
Noodle.create(level: 2, sentence: "麺、柔らかめでツルンとイケちゃうもの。")
Noodle.create(level: 2, sentence: "麺、つるりとした舌触りのもの。")
Noodle.create(level: 2, sentence: "麺、いつもより柔らかめのもの。")
Noodle.create(level: 2, sentence: "麺、柔らかめな極太麺、液体アブラ纏ってる。")
Noodle.create(level: 2, sentence: "麺、汁絡み、歯切れ楽しい、パッツ麺。")
Noodle.create(level: 2, sentence: "麺、液体アブラ纏ったムッチムチ麺。")
Noodle.create(level: 2, sentence: "麺、ザックザク、味しみ感があるもの。")
Noodle.create(level: 2, sentence: "麺、柔らかい麺。汁染み感もあり。")
Noodle.create(level: 2, sentence: "麺、パツ食感に汁染みたもの。")
Noodle.create(level: 2, sentence: "麺、チョイデロな柔らかめのもの。")
Noodle.create(level: 2, sentence: "麺、パツパツ麺。汁がまあまあ絡む。")
Noodle.create(level: 2, sentence: "麺、ザクザクと食える麺。")
#レベル3
Noodle.create(level: 3, sentence: "麺、ウマい。メッチャ柔らかプッルプル。")
Noodle.create(level: 3, sentence: "麺、柔らかめな仕上がり嬉しい味染み麺。")
Noodle.create(level: 3, sentence: "麺、柔らかめで醤油染みててウマい。")
Noodle.create(level: 3, sentence: "麺、コレ好き。味染みまくりィ。")
Noodle.create(level: 3, sentence: "麺、弾力ある俺好みなもの。")
Noodle.create(level: 3, sentence: "麺、プリとした食感、ズババと啜れる俺好みのもの。")
Noodle.create(level: 3, sentence: "麺、クッニュクニュ。アブラ纏ってウマい。")
Noodle.create(level: 3, sentence: "麺、柔らかくて味染み感ほど良い。")
Noodle.create(level: 3, sentence: "麺、ザックザク頬張れて、口溶け感俺好み。")
Noodle.create(level: 3, sentence: "味染みた麺、喰い出したら夢中。ウマい。")
Noodle.create(level: 3, sentence: "麺、液体アブラ纏った麺、汁染み具合俺好み。")
Noodle.create(level: 3, sentence: "麺、ちょいパツな仕上がりに汁メッチャ染みててウマし。")
Noodle.create(level: 3, sentence: "麺、プルンと踊る食感楽しめるもの。俺好み。")
Noodle.create(level: 3, sentence: "麺、汁メッチャ染みてて、たまらなくウマい。")
Noodle.create(level: 3, sentence: "麺、柔らかくて甘ウマ汁染みててウンメ〜。")
Noodle.create(level: 3, sentence: "麺、醤油染みたもの。ウンメ〜。")
#レベル4
Noodle.create(level: 4, sentence: "麺、柔らか嬉しい、喰い出したらとまんないもの！")
Noodle.create(level: 4, sentence: "麺、柔らかくてウッメェェッ！")
Noodle.create(level: 4, sentence: "麺、ホクと柔らか味染みててウンメ〜ッ！")
Noodle.create(level: 4, sentence: "麺、ユッルユルに柔らか激しく俺好みのもの。メッチャウマ！")
Noodle.create(level: 4, sentence: "麺、醤油染みててプルプル食感の太麺、メッチャウンメ〜ッ！")
Noodle.create(level: 4, sentence: "麺、液体アブラ甘んめ〜っ！醤油効いてウンメ〜ッ！")
Noodle.create(level: 4, sentence: "クニュ麺ヤバすぎ、ブタプリップリぃ！")
Noodle.create(level: 4, sentence: "麺、ウンメ〜ッ！最ッ高でしょ！")
Noodle.create(level: 4, sentence: "麺、ウマい、ウマ過ぎる。押し寄せる多幸感。夢見心地で貪るぅ！")
Noodle.create(level: 4, sentence: "麺、デロンデロンなデロ麺がメッチャ柔らかくて、たまんないぃ！極めて俺好みのもの。")
Noodle.create(level: 4, sentence: "麺、髑髏汁染みた麺、超堪んない！")
Noodle.create(level: 4, sentence: "麺、コレ好きィ！ツルンッ！モチッ！として汁メッチャ染みたもの。ウンメ〜ッ！")
Noodle.create(level: 4, sentence: "麺、甘ウマ汁染みてて、トロける柔らかさの俺好みな麺。ウンメ〜！")
Noodle.create(level: 4, sentence: "麺、クニュとした食感の麺がアブラ纏ってウンメ〜！")
Noodle.create(level: 4, sentence: "麺、モソとした素朴な食感俺好み。メッチャウンメ〜ッ！")
Noodle.create(level: 4, sentence: "麺、プルプル食感、俺好み。メッチャウンメ〜ッ！")
Noodle.create(level: 4, sentence: "麺、メッチャ味染みた、口の中で、ふあとほどける、ほぼ咀嚼不要なもの。最ッ高に俺好み！！")
Noodle.create(level: 4, sentence: "麺、ウッメェェェェェッッ！！クニュとした食感の、味染みた最ッ高にウマい麺ッ！！")
Noodle.create(level: 4, sentence: "麺、このクニュ感、この柔らかさ、至高過ぎィ！")
Noodle.create(level: 4, sentence: "麺、クニュッと柔らか、ふあとほどける口溶け、最ッ高でしょ！")
#レベル5
Noodle.create(level: 5, sentence: "麺、柔らか！味染み！アブラ絡んで、神域ッ！！")
Noodle.create(level: 5, sentence: "麺、ムチとした麺、ザクと啜ってウッメェェッ！！神域のなか、夢中で掻き込む。")
Noodle.create(level: 5, sentence: "麺、柔らかな仕上がり嬉しい、味メッチャ染みた最ッ高にウマい神麺！！")
Noodle.create(level: 5, sentence: "麺、汁染みた麺ハフハフ啜る。ウマ過ぎィ！！俺の理想二郎のひとつ降臨してた。")
Noodle.create(level: 5, sentence: "麺、この麺、至高過ぎぃ！！クニュ食感に、汁染みた神域のもの。")
Noodle.create(level: 5, sentence: "麺、神域のデッロデロ。汁染み極まり、奮えて啜る。至高過ぎィ！！")
Noodle.create(level: 5, sentence: "麺、この麺、神話級ッ！！語り継がれるべき味染み感。神と戯れてたら丼カラになってた。")
Noodle.create(level: 5, sentence: "麺、歯切れ最高のプツパツ麺。メッチャクチャ俺好みィ！！神麺ここに降臨。")
Noodle.create(level: 5, sentence: "麺、プルップルに柔らかい、最ッ高な食感の麺。旨味濃厚汁染みて、奮えるしかない神域の麺！！")


#スープテーブル
#レベル1
Soup.create(level: 1, sentence: "汁、いささかウスメ。")
Soup.create(level: 1, sentence: "汁、いささかカラすぎ。")
Soup.create(level: 1, sentence: "汁、いささかウスメも、卓上醤油で俺好みに調整可能。")
Soup.create(level: 1, sentence: "汁、甘みとウマ味あと少し。")
Soup.create(level: 1, sentence: "汁、焦げ味感じるもの。")
Soup.create(level: 1, sentence: "汁、肉そば風味の微妙なもの。")
Soup.create(level: 1, sentence: "汁、塩気マイルドすぎなもの。")
Soup.create(level: 1, sentence: "汁、ポテンシャルは感じるものの、いささか薄めな汁。")
#レベル2
Soup.create(level: 2, sentence: "汁、ミルキィなニンニク溶けた汁。")
Soup.create(level: 2, sentence: "汁、生姜の風味効いた汁。")
Soup.create(level: 2, sentence: "汁、塩気効いた汁。")
Soup.create(level: 2, sentence: "汁、優しい味わい、癒し汁。")
Soup.create(level: 2, sentence: "汁、コクあって風味効いた汁。")
Soup.create(level: 2, sentence: "汁、ウマ味のある汁。")
Soup.create(level: 2, sentence: "汁、ウマ味出て醤油利いてる塩気汁。")
Soup.create(level: 2, sentence: "汁、旨味の効いた甘口テイスト。")
Soup.create(level: 2, sentence: "汁、まあ好みの醤油加減なもの。")
Soup.create(level: 2, sentence: "汁、これはこれで俺好み。")
Soup.create(level: 2, sentence: "汁、熱ッツ、ウッメェッ！言いながら飲んだ。")
#レベル3
Soup.create(level: 3, sentence: "汁、メッチャ濃い。ウマ味極めし汁。")
Soup.create(level: 3, sentence: "汁、甘くてウンメ〜汁。")
Soup.create(level: 3, sentence: "汁、ニンニク溶けた汁。ウマい。卓上醤油いい仕事。")
Soup.create(level: 3, sentence: "汁、ウマい。優しい味わい沁み渡る。")
Soup.create(level: 3, sentence: "汁、旨味と醤油利いた俺好みのキリリ汁。")
Soup.create(level: 3, sentence: "汁、ミルキィでアッツアツ。野菜にメッチャ合う汁。")
Soup.create(level: 3, sentence: "汁、醤油効いたコクのある汁ウンメ〜。")
Soup.create(level: 3, sentence: "汁、ウマ味と醤油効いて、俺好みのウマみ。")
Soup.create(level: 3, sentence: "汁、若干の塩味の中にウマ味あり。")
Soup.create(level: 3, sentence: "汁、スッキリした味わい、ゴクゴクイケる汁。")
Soup.create(level: 3, sentence: "汁、ウマ味効いたミルキィ汁ウンメ〜。")
Soup.create(level: 3, sentence: "汁、優しい味わいの汁。ウンメ〜。")
Soup.create(level: 3, sentence: "汁、ミルキィでコクありウンメ〜。")
Soup.create(level: 3, sentence: "汁、コクすんげ〜。たまらず飲んだ。")
Soup.create(level: 3, sentence: "汁、醤油がいい塩梅に効いてて、ニンニク溶けてウマし。")
Soup.create(level: 3, sentence: "汁、麺と一緒にズル喰う。ウンメ〜。")
Soup.create(level: 3, sentence: "汁、旨味濃厚、塩気ガツンと利いた汁。ゴクゴク、ウッメェ。")
#レベル4
Soup.create(level: 4, sentence: "汁、液体アブラ効いてて最高にウンメ〜！")
Soup.create(level: 4, sentence: "汁、ウマ味すんげ〜っ！！ニンニク溶けてウマさ倍増、味最ッ高なもの。")
Soup.create(level: 4, sentence: "汁、旨味最ッ高に感じる汁。丼から口離せない、ウッメェェッ！")
Soup.create(level: 4, sentence: "汁、ウッメェェッ！ミルキィ汁に玉子メッチャクチャ合う！")
Soup.create(level: 4, sentence: "汁、ウッメェェッ！肉のウマ味と液体アブラの甘み効いたメチャウマ汁ぅ！")
Soup.create(level: 4, sentence: "汁、濃いめに効いた醤油で堪らなくウッメェェッ！")
Soup.create(level: 4, sentence: "汁、ウッメェェッ！！生姜ふあと香る堪らなく最高に俺好みな汁。")
Soup.create(level: 4, sentence: "汁、ウマ味利いた安定汁。最ッ高にウマい！")
Soup.create(level: 4, sentence: "汁、ウンメ〜〜ッ！味の加減いい感じ、飲みやすい汁！ニンニク溶けてウマさ最高に極まる。")
Soup.create(level: 4, sentence: "汁、ウンメ〜ッ！煮干の旨さ極めた感動汁。")
Soup.create(level: 4, sentence: "汁、濃縮した様なテイストッ！メッチャ中毒性有り、飲まずには居られないもの。")
Soup.create(level: 4, sentence: "汁、醤油利いた汁、ニンニク溶けて奮えるウマさ！")
Soup.create(level: 4, sentence: "汁、ウマさスカウター振り切れ爆発なウマさ！！")
Soup.create(level: 4, sentence: "汁、圧倒的なウマ味、受容体の許容値オーバー。感激で奮え止まらない至高の汁。")
Soup.create(level: 4, sentence: "汁、ヤサイとの相性もバツグンのコクウマ汁！最高のウマさ！")
Soup.create(level: 4, sentence: "汁、旨味と醤油とアブラの甘み利いた、夢中になれる興奮汁ぅ！")
Soup.create(level: 4, sentence: "汁、ウッメぇぇぇッ！最ッ高でしょこの汁。体求める必須汁ぅ！")
Soup.create(level: 4, sentence: "汁、濃厚トロットロな汁に醤油バッチリ利いた味。ウッメェェッ！")
Soup.create(level: 4, sentence: "汁、タプンとコラーゲン感じる、醤油利いた汁。ウッメェェッ！")
Soup.create(level: 4, sentence: "汁、塩気アブラの凶暴系。ウマさ爆発のなか、夢中で貪った。")
Soup.create(level: 4, sentence: "汁、醤油キリと利いた、飲んでヨシ！麺と絡めてヨシ！な、至高汁。")
Soup.create(level: 4, sentence: "汁、麺と一緒にズルと啜れば、も〜タマらんッ！これぞ至高汁。")
#レベル5
Soup.create(level: 5, sentence: "汁、ウマ味爆発ッ！奮える神の汁っ！！")
Soup.create(level: 5, sentence: "汁、一口で虜ッ！神域での恍惚テイストッ！！")
Soup.create(level: 5, sentence: "汁、本店彷彿とさせるウマさ極めたKAMI汁ウッメェェッ！！")
Soup.create(level: 5, sentence: "汁、液体アブラ効いてて激しくウッメェェッ！！震え抑えながらKAMI汁飲んだ。")
Soup.create(level: 5, sentence: "汁、コレメッチャ好きィ！！塩気効いた汁で神域。")
Soup.create(level: 5, sentence: "し、汁、神域ィ！！二郎観大幅に書き換わる衝撃的ウマ味、奮えながら貪る。")
Soup.create(level: 5, sentence: "汁、一口で、奮えMAX、至高の神汁。")
Soup.create(level: 5, sentence: "汁、コクうま汁、神の汁。一口で神の領域に突入。")
Soup.create(level: 5, sentence: "汁、コクうま汁、旨味と塩気のPAPP汁。一口で完飲へのビジョン明確になる最上最高の神汁ぅ！！")
Soup.create(level: 5, sentence: "汁、ミルキィでウマ味極まる夢中の神汁っ！！")
Soup.create(level: 5, sentence: "汁、一口啜った瞬間、完飲が約束されるもの。神話級。")
Soup.create(level: 5, sentence: "汁、神域のバランス汁。我を忘れる夢中汁。奮えながら啜る。")


#豚テーブル
#レベル1
Pork.create(level: 1, sentence: "ブタ、変な柔らかさのもの。")
Pork.create(level: 1, sentence: "ブタ、まあしっとりしたもの。")
Pork.create(level: 1, sentence: "ブタ、少しだけ肉肉しい仕上がり。")
Pork.create(level: 1, sentence: "ブタ、微妙にトロっとした変に柔らかなもの。")
Pork.create(level: 1, sentence: "ブタ、フッワフワな肉肉さが足りないもの。")
Pork.create(level: 1, sentence: "ブタ、カラメの塩気で脂身の甘みがあと少し。")
Pork.create(level: 1, sentence: "ブタ、脂身プリップリ要素があと一歩。")
Pork.create(level: 1, sentence: "ブタ、プルンと甘〜いだけのもの。")
Pork.create(level: 1, sentence: "ブタ、プルンとトロけるが、甘み広がってほしいもの。")
Pork.create(level: 1, sentence: "ブタ、いささか臭み感じるものの、許容範囲内のもの。")
#レベル2
Pork.create(level: 2, sentence: "ブタ、肉ホロな食感のもの。")
Pork.create(level: 2, sentence: "ブタ、脂身甘し。")
Pork.create(level: 2, sentence: "ブタ、プルンと柔らか。")
Pork.create(level: 2, sentence: "ブタ、ミチとした肉々しい食感のもの。")
Pork.create(level: 2, sentence: "ブタ、プリップリでゴッロゴロ。")
Pork.create(level: 2, sentence: "ブタ、肉らしい噛み応えのものがゴッロゴロ。")
Pork.create(level: 2, sentence: "ブタ、フワフワで脂身甘いもの。")
Pork.create(level: 2, sentence: "ブタ、トロとしてまあウマい。")
Pork.create(level: 2, sentence: "ブタ、まあ味しみててウンメ〜。")
Pork.create(level: 2, sentence: "ブタ、ふあトロ食感なもの。")
Pork.create(level: 2, sentence: "ブタ、適度にパサって、汁吸って、GOOD。")
Pork.create(level: 2, sentence: "ブタ、ほぐれるような食感のものがゴッロゴロ。")
#レベル3
Pork.create(level: 3, sentence: "ブタ、プリリとした豚、この食感は俺好み。")
Pork.create(level: 3, sentence: "ブタ、ほぐれる食感俺好み。")
Pork.create(level: 3, sentence: "ブタ、噛むほどウマい、スルメブタ。")
Pork.create(level: 3, sentence: "ブタ、トッロトロ！くち溶けふわりブタ。")
Pork.create(level: 3, sentence: "ブタ、大ぶりで柔らか、ミチとした食感のブタ。")
Pork.create(level: 3, sentence: "ブタ、塩気効いたブタ、メッチャ好きィ。")
Pork.create(level: 3, sentence: "ブタ、強めな塩気、食感は俺好みのもの。")
Pork.create(level: 3, sentence: "ブタ、ほぐれる食感のブタ、強めに利いた塩気に夢中。")
Pork.create(level: 3, sentence: "ブタ、ウンメッ〜。肉喰った感マシマシなもの。")
Pork.create(level: 3, sentence: "ブタ、ほどける食感のもの。ウンメ〜ッ。")
Pork.create(level: 3, sentence: "ブタ、トロットロのもの。脂身あんめ〜っ。")
Pork.create(level: 3, sentence: "ブタ、肉のウマ味堪能できるプリリとしたもの。")
Pork.create(level: 3, sentence: "ブタ、歯を立てた途端、ホロリ解れるウマ味ブタ。")
Pork.create(level: 3, sentence: "ブタ、脂身プリップリで甘ウマなもの。")
Pork.create(level: 3, sentence: "ブタ、ゴロっとしたもの。肉々しくウマい。")
Pork.create(level: 3, sentence: "ブタ、ほぐれるような食感のブタ、脂身トロトロ。")
#レベル4
Pork.create(level: 4, sentence: "ブタ、脂身トロォ、肉ホロッ！ドッサリ！")
Pork.create(level: 4, sentence: "ブタ、端ブタ有りッ！ホッロホロ！")
Pork.create(level: 4, sentence: "ブタ、ウッメ〜ッ！思わず声が出てしまった。")
Pork.create(level: 4, sentence: "ブタ、ドッサリ。脂身甘くてウンメ〜ッ！")
Pork.create(level: 4, sentence: "ブタ、ほぐれる食感、タレに浸って激しく旨いぃ！")
Pork.create(level: 4, sentence: "ブタ、ウンメ〜ッ！ウマ味に夢中、思わず震えた。")
Pork.create(level: 4, sentence: "端ブタウンメ〜！脂身ネットリトロントロン！")
Pork.create(level: 4, sentence: "ブタ、やっわらけ〜！摘んだだけでホロと崩れるもの。")
Pork.create(level: 4, sentence: "ブタ、プリップリの脂身。キメの細かい肉質の柔らかブタっ！")
Pork.create(level: 4, sentence: "ブタ、噛みしめるとジューシィッ！ウッメェェェッ！！")
Pork.create(level: 4, sentence: "ブタ、ウッメェェェェッ！！極めてデッロデロ、メッチャ俺好み！")
#レベル5
Pork.create(level: 5, sentence: "ブタ、ウッメェェッ！！神域のホロ肉。完全に虜。")
Pork.create(level: 5, sentence: "ブタ、端豚、巻豚、神域ィ！！")
Pork.create(level: 5, sentence: "ブタ、ホロホロジューシー至高の一品。神域で安定。")
Pork.create(level: 5, sentence: "ブタ、ほぐれる食感、ブタ切れが無念に思えるもの。これぞ神域のブタ。")
Pork.create(level: 5, sentence: "ブタ、塩気とアブラの興奮仕様ッ！！我忘れて貪り飲んだ神話ブタ。")
Pork.create(level: 5, sentence: "ブタ、プリと柔らか、味染みた最ッ高にウマい神ブタs！！")
Pork.create(level: 5, sentence: "ブタ、ウッメェェッ！！トロッとほろけて神域で安定。")
Pork.create(level: 5, sentence: "ブタ、しっとりムッチリ神話級！！我忘れて貪れるもの。")
Pork.create(level: 5, sentence: "ブタ、天に乞う、ブタ肉10枚、喰う権利。神域最高、超ウッメェェェッ！！")
Pork.create(level: 5, sentence: "ブタ、肉のウマ味爆発ッ！！夢中で頬張った。神域にて感涙。")
Pork.create(level: 5, sentence: "ブタ、肉質しっかり、ジューシィで、純粋に神なるもの。")
Pork.create(level: 5, sentence: "ブタ、ウッメェェッ！！フワフワで脂身甘い神域ぶた。")


#(全行数) - (文字行数22行) = 現在200データ
