#麺テーブル
#レベル1
Noodle.create(level: 1, sentence: "麺、ムチとした食感のもの。")
Noodle.create(level: 1, sentence: "麺、カタメな仕上がり。")
Noodle.create(level: 1, sentence: "麺、プルプルな食感のもの。")
Noodle.create(level: 1, sentence: "麺、柔らかめな仕上がり。")
Noodle.create(level: 1, sentence: "麺、ズババと啜れるもの。")
Noodle.create(level: 1, sentence: "麺、汁染みた仕上がり。")
Noodle.create(level: 1, sentence: "麺、クニュクニュな食感のもの。")
Noodle.create(level: 1, sentence: "麺、ウマい汁染みた仕上がり。")
Noodle.create(level: 1, sentence: "麺、ウマ味凝縮な仕上がり。")
Noodle.create(level: 1, sentence: "麺、歯切れ楽しい仕上がり。")
#レベル2
Noodle.create(level: 2, sentence: "麺、カタメな食感のもの。ウマい。")
Noodle.create(level: 2, sentence: "麺、モソとした素朴な食感俺好み。")
Noodle.create(level: 2, sentence: "麺、プルプル食感、俺好み。")
Noodle.create(level: 2, sentence: "麺、カタメな仕上がりのもの。ウンメ〜。")
Noodle.create(level: 2, sentence: "麺、いつもより柔らかめのもの。")
Noodle.create(level: 2, sentence: "麺、柔らかめな極太麺、液体アブラ纏ってウマい。")
Noodle.create(level: 2, sentence: "麺、汁絡み、歯切れ楽しい、パッツ麺。")
Noodle.create(level: 2, sentence: "麺、ザックザク、味しみ感が俺好み。")
Noodle.create(level: 2, sentence: "麺、俺好みの柔らかさ。汁染み感もヨシ。")
Noodle.create(level: 2, sentence: "麺、パツ食感に汁染みたもの。")
Noodle.create(level: 2, sentence: "麺、チョイデロな柔らかめのもの。")
#レベル3
Noodle.create(level: 3, sentence: "麺、こりゃウマい！メッチャ柔らかプッルプル。")
Noodle.create(level: 3, sentence: "麺、柔らかめで醤油染みててウマい。")
Noodle.create(level: 3, sentence: "麺、コレ好きィ！味染みまくりィ！")
Noodle.create(level: 3, sentence: "麺、プリとした食感、ズババと啜れる俺好みのもの。")
Noodle.create(level: 3, sentence: "麺、クッニュクニュ。アブラ纏ってメッチャウマ。")
Noodle.create(level: 3, sentence: "麺、ウッメェェッ！柔らかくて味染み感バツグンっ！")
Noodle.create(level: 3, sentence: "味染みた麺、喰い出したら夢中。奮え止まらない。")
Noodle.create(level: 3, sentence: "麺、液体アブラ纏った麺、汁染み具合俺好み。")
Noodle.create(level: 3, sentence: "麺、ちょいパツな仕上がりに汁メッチャ染みててウマし。")
Noodle.create(level: 3, sentence: "麺、プルンと踊る食感楽しめるもの。")
Noodle.create(level: 3, sentence: "麺、醤油染みたもの。玉子絡めてウッメェ！") #topping = 味玉
#レベル4
Noodle.create(level: 4, sentence: "麺、柔らか嬉しい、喰い出したらとまんないもの！")
Noodle.create(level: 4, sentence: "麺、柔らかくてウッメェェッ！")
Noodle.create(level: 4, sentence: "麺、ホクと柔らか味染みててウンメ〜ッ！")
Noodle.create(level: 4, sentence: "麺、ユッルユルに柔らか激しく俺好みのもの。")
Noodle.create(level: 4, sentence: "麺、醤油染みててプルプル食感の太麺、メッチャウンメ〜ッ！")
Noodle.create(level: 4, sentence: "麺、液体アブラ甘んめ〜っ！醤油効いてウンメ〜ッ！")
Noodle.create(level: 4, sentence: "クニュ麺ヤバすぎ、ブタプリップリぃ！")
Noodle.create(level: 4, sentence: "麺、ウンメ〜ッ！！最ッ高でしょ！")
Noodle.create(level: 4, sentence: "麺、髑髏汁染みた麺、超堪んない！")
Noodle.create(level: 4, sentence: "麺、コレ好きィ！ツルンッ！モチッ！として汁メッチャ染みたもの。")
Noodle.create(level: 4, sentence: "麺、甘ウマ汁染みてて、トロける柔らかさの俺好みな麺。")
Noodle.create(level: 4, sentence: "麺、クニュとした食感の麺がアブラ纏ってウンメ〜！")
#レベル5
Noodle.create(level: 5, sentence: "麺、このクニュ感、この柔らかさ、至高過ぎィ！")
Noodle.create(level: 5, sentence: "麺、クニュッと柔らか、ふあとほどける口溶け、最ッ高でしょ！")
Noodle.create(level: 5, sentence: "麺、柔らか！味染み！アブラ絡んで、ウッメェェッ！")
Noodle.create(level: 5, sentence: "麺、ムチとした麺、ザクと啜ってウッメェェッ！夢中で掻き込む。")
Noodle.create(level: 5, sentence: "麺、柔らかな仕上がり嬉しい、味メッチャ染みた最ッ高にウマい麺。")
Noodle.create(level: 5, sentence: "麺、汁染みた麺ハフハフ啜る。ウマ過ぎィ！俺の理想二郎のひとつ降臨してた。")
Noodle.create(level: 5, sentence: "麺、この麺、至高過ぎぃ！クニュ食感に、汁染みた神域のもの。")
Noodle.create(level: 5, sentence: "麺、神域のデッロデロ。汁染み極まり、奮えて啜る。")
Noodle.create(level: 5, sentence: "麺、この麺、神話級ッ！語り継がれるべき味染み感。神と戯れてたら丼カラになってた。")


#スープテーブル
#レベル1
Soup.create(level: 1, sentence: "汁、いささかウスメ。")
Soup.create(level: 1, sentence: "汁、いささかカラすぎ。")
Soup.create(level: 1, sentence: "汁、いささかウスメも、卓上醤油で俺好みに調整可能。")
Soup.create(level: 1, sentence: "汁、甘みとウマ味あと少し。")
Soup.create(level: 1, sentence: "汁、焦げ味感じるもの。")
Soup.create(level: 1, sentence: "汁、肉そば風味のもの。")
Soup.create(level: 1, sentence: "汁、塩気マイルドなもの。")
#レベル2
Soup.create(level: 2, sentence: "汁、ミルキィなニンニク溶けてウマい汁。")
Soup.create(level: 2, sentence: "汁、生姜の風味効いたウマい汁。")
Soup.create(level: 2, sentence: "汁、コレ好きィ！塩気効いた汁。")
Soup.create(level: 2, sentence: "汁、コクあってウッメェェッ！")
Soup.create(level: 2, sentence: "汁、ウマ味たっぷりの汁。ウッメェェッ！")
Soup.create(level: 2, sentence: "汁、ニンニク溶けてウマし。卓上醤油いい仕事。")
Soup.create(level: 2, sentence: "汁、ウンメ〜！")
Soup.create(level: 2, sentence: "汁、ウマ味よく出て醤油利いた塩気汁。")
Soup.create(level: 2, sentence: "汁、旨味の効いた甘口なテイスト。")
#レベル3
Soup.create(level: 3, sentence: "汁、メッチャ濃いッ！ウマ味極めし汁。")
Soup.create(level: 3, sentence: "汁、甘くてウッメェェッ！")
Soup.create(level: 3, sentence: "汁、醤油効いたコクのある汁ウンメ〜。")
Soup.create(level: 3, sentence: "汁、ウマ味と醤油効いて、メッチャウマ。")
Soup.create(level: 3, sentence: "汁、辛味の中にウマ味ありッ！")
Soup.create(level: 3, sentence: "汁、ウマ味効いたミルキィ汁ウンメ〜ッ！")
Soup.create(level: 3, sentence: "汁、優しい味わいの汁。思わず貪り飲んだ。")
Soup.create(level: 3, sentence: "汁、ミルキィでコクありウッメェッ！")
Soup.create(level: 3, sentence: "汁、玉子落としてズル喰う。ウッメェッ！") #topping = 味玉
Soup.create(level: 3, sentence: "汁、旨味濃厚、塩気ガツンと利いた汁。玉子落としてウッメェ！") #topping = 味玉
Soup.create(level: 3, sentence: "汁、コクすんげ〜ッ！たまらず飲んだ。")
#レベル4
Soup.create(level: 4, sentence: "汁、液体アブラ効いててウンメ〜！")
Soup.create(level: 4, sentence: "汁、ウッメェェッ！ミルキィ汁に玉子メッチャ合う！")
Soup.create(level: 4, sentence: "汁、ウッメェェッ！肉のウマ味と液体アブラの甘み効いたメチャウマ汁。")
Soup.create(level: 4, sentence: "汁、濃いめに効いた醤油で堪らなくウッメェェッ！")
Soup.create(level: 4, sentence: "汁、ウッメェェッ！生姜ふあと香る堪らなく俺好みな汁。")
Soup.create(level: 4, sentence: "汁、熱ッツ、ウッメェッ！言いながら飲んだ。")
Soup.create(level: 4, sentence: "汁、ウマ味利いた安定汁。最ッ高にウマい。")
Soup.create(level: 4, sentence: "汁、醤油利いた汁、ニンニク溶けて奮えるウマさ。")
Soup.create(level: 4, sentence: "汁、濃厚トロットロな汁に醤油バッチリ利いたひばり味。") #shop_name = ひばり
Soup.create(level: 4, sentence: "汁、タプンとコラーゲン感じる、醤油利いたひばり汁。") #shop_name = ひばり
Soup.create(level: 4, sentence: "汁、醤油キリと利いた、飲んでヨシ！玉子溶かしてヨシ！な、至高汁。") #topping = 味玉
Soup.create(level: 4, sentence: "汁、仕舞い、汁に玉子落として玉子汁。ズルと啜れば、も〜タマらんッ。") #topping = 味玉
#レベル5
Soup.create(level: 5, sentence: "汁、肉のウマ味爆発ッ！奮える汁っ！！")
Soup.create(level: 5, sentence: "汁、一口で虜ッ！恍惚テイストッ！")
Soup.create(level: 5, sentence: "汁、本店彷彿とさせるウマさ極めた汁ウッメェェッ！")
Soup.create(level: 5, sentence: "汁、液体アブラ効いてて激しくウッメェェッ！")
Soup.create(level: 5, sentence: "汁、コレメッチャ好きィ！塩気効いた汁で神域。")
Soup.create(level: 5, sentence: "し、汁、神域ィ！！二郎観大幅に書き換わる衝撃的ウマ味、奮えながら貪る。")
Soup.create(level: 5, sentence: "汁、一口で、奮えMAX、至高汁。")
Soup.create(level: 5, sentence: "汁、コクうま汁、神の汁。")
Soup.create(level: 5, sentence: "汁、ミルキィでウマ味極まる夢中汁っ！")
Soup.create(level: 5, sentence: "汁、一口啜った瞬間、完飲が約束されるもの。神話級。")
Soup.create(level: 5, sentence: "汁、天地返して、一味を天空落とせば、ウマさに体もあったまる。震え抑えた。") #topping = 味玉


#豚テーブル
#レベル1
Pork.create(level: 1, sentence: "ブタ、プルンと柔らかいもの。")
Pork.create(level: 1, sentence: "ブタ、しっとりしたもの。")
Pork.create(level: 1, sentence: "ブタ、肉肉しい仕上がり。")
Pork.create(level: 1, sentence: "ブタ、トロと柔らかなもの。")
Pork.create(level: 1, sentence: "ブタ、フッワフワに柔らかさ。")
Pork.create(level: 1, sentence: "ブタ、カラメの塩気で脂身の甘み際立つもの。")
Pork.create(level: 1, sentence: "ブタ、脂身プリップリ。")
Pork.create(level: 1, sentence: "ブタ、プルンと甘〜い脂身のもの。")
Pork.create(level: 1, sentence: "ブタ、プルンとトロけて、甘み広がる。")
Pork.create(level: 1, sentence: "ブタ、脂身あんめ〜。")
#レベル2
Pork.create(level: 2, sentence: "ブタ、肉ホロな食感のもの。")
Pork.create(level: 2, sentence: "ブタ、脂身甘くてウンメ〜。")
Pork.create(level: 2, sentence: "ブタ、ミチとした肉々しい食感のもの。")
Pork.create(level: 2, sentence: "ブタ、プリップリでゴッロゴロ。")
Pork.create(level: 2, sentence: "ブタ、フワフワで脂身甘いもの。")
Pork.create(level: 2, sentence: "ブタ、トロとしてウマい。")
Pork.create(level: 2, sentence: "ブタ、味しみててウンメ〜。")
Pork.create(level: 2, sentence: "ブタ、ふあトロでウンメ〜。")
Pork.create(level: 2, sentence: "ブタ、適度にパサって、汁吸って、GOOD。")
Pork.create(level: 2, sentence: "ブタ、ほぐれるような食感のものがゴッロゴロ。")
#レベル3
Pork.create(level: 3, sentence: "ブタ、プリリとした豚、メッチャウマ。")
Pork.create(level: 3, sentence: "ブタ、ほぐれる食感俺好み。")
Pork.create(level: 3, sentence: "ブタ、トッロトロ！くち溶けふわりブタ。")
Pork.create(level: 3, sentence: "ブタ、大ぶりで柔らか、ミチとした食感のブタ。")
Pork.create(level: 3, sentence: "ブタ、塩気効いたブタ、メッチャ好きィ！")
Pork.create(level: 3, sentence: "ブタ、強めな塩気の俺好みのもの。")
Pork.create(level: 3, sentence: "ブタ、ほぐれる食感のブタ、強めに利いた塩気に夢中。")
Pork.create(level: 3, sentence: "ブタ、ウンメッ〜。肉喰った感マシマシなもの。")
Pork.create(level: 3, sentence: "ブタ、ほどける食感のもの。ウンメ〜ッ！")
Pork.create(level: 3, sentence: "ブタ、肉のウマ味堪能できるプリリとしたもの。")
#レベル4
Pork.create(level: 4, sentence: "ブタ、脂身トロォ、肉ホロッ！ドッサリ！")
Pork.create(level: 4, sentence: "ブタ、ドッサリ。脂身甘くてウンメ〜ッ！")
Pork.create(level: 4, sentence: "ブタ、ウッメェェッ！神域のホロ肉。")
Pork.create(level: 4, sentence: "ブタ、ウッメェェッ！フワフワで脂身甘い神域ぶた。")
Pork.create(level: 4, sentence: "ブタ、ウンメ〜ッ！ウマ味に夢中、思わず飲んだ。")
Pork.create(level: 4, sentence: "ブタ、端豚、巻豚、神域ィ！")
Pork.create(level: 4, sentence: "端ブタウンメ〜！脂身ネットリトロントロン。")
Pork.create(level: 4, sentence: "ブタ、やっわらけ〜！摘んだだけでホロと崩れるもの。")
Pork.create(level: 4, sentence: "ブタ、プリップリの脂身。キメの細かい肉質の柔らかブタっ。")
Pork.create(level: 4, sentence: "ブタ、噛みしめるとジューシィッ！超ウッメェェェッ！！")
#レベル5
Pork.create(level: 5, sentence: "ブタ、端ブタ有りッ！ホッロホロ！")
Pork.create(level: 5, sentence: "ブタ、ほぐれる食感、ブタ切れが無念に思えるもの。")
Pork.create(level: 5, sentence: "ブタ、塩気とアブラの興奮仕様ッ！我忘れて貪り飲んだ。")
Pork.create(level: 5, sentence: "ブタ、プリと柔らか、味染みた最ッ高にウマいぶた。")
Pork.create(level: 5, sentence: "ブタ、ウッメェェッ！神域で安定。")
Pork.create(level: 5, sentence: "ブタ、しっとりムッチリ最ッ高！我忘れて貪れるもの。")
Pork.create(level: 5, sentence: "ブタ、天に乞う、ブタ肉10枚、喰う権利。")
Pork.create(level: 5, sentence: "ブタ、肉のウマ味爆発ッ！夢中で頬張った。感涙。")
Pork.create(level: 5, sentence: "ブタ、天に乞う、ブタ肉10枚、喰う権利。")
Pork.create(level: 5, sentence: "ブタ、ウッメェェェェッ！！！極めてデッロデロ、メッチャ俺好み。")
